# Machine Learning 2023/2024

## Third Home Assignment

**Group Number:** 10

**Group Elements:**
- André Santos (fc53323)
- Filipe Santos (fc53304)
- João Martins (fc62532)
- Rúben Torres (fc62531)

**Hours Worked:**
- André Santos (10h)
- Filipe Santos (10h)
- João Martins (10h)
- Rúben Torres (10h)

### Imports

In [2]:
import pandas as pd
import pickle
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier, plot_tree
from sklearn.linear_model import LinearRegression, Ridge, Lasso, LogisticRegression
from statsmodels.api import OLS, add_constant
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
from sklearn.metrics import explained_variance_score, mean_squared_error, max_error, mean_absolute_error
from scipy.stats import pearsonr
from sklearn import tree
from sklearn.metrics import precision_score, recall_score, f1_score, matthews_corrcoef, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import (PowerTransformer)
from sklearn.decomposition import PCA
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.feature_selection import SequentialFeatureSelector


### Loading and understanding the Dataset

In [3]:
unpickled_df = pd.read_pickle("drd2_data.pickle")
unpickled_df

(array([[541.28013798, 541.656     ,  10.        , ...,   0.        ,
           0.        ,   0.        ],
        [426.19771382, 426.582     ,   5.        , ...,   0.        ,
           0.        ,   0.        ],
        [348.18377801, 348.446     ,   4.        , ...,   0.        ,
           0.        ,   0.        ],
        ...,
        [510.31787387, 510.802     ,   4.        , ...,   0.        ,
           0.        ,   0.        ],
        [393.18748348, 393.556     ,   4.        , ...,   0.        ,
           0.        ,   0.        ],
        [484.0561233 , 485.462     ,   6.        , ...,   0.        ,
           0.        ,   0.        ]]),
 array([[337.1920902 , 337.895     ,   4.        , ...,   0.        ,
           0.        ,   0.        ],
        [357.1762501 , 357.519     ,   3.        , ...,   0.        ,
           0.        ,   0.        ],
        [571.22715538, 572.171     ,   7.        , ...,   0.        ,
           0.        ,   0.        ],
        ...,


In [4]:
print(type(unpickled_df[0]))
unpickled_df[0].shape

<class 'numpy.ndarray'>


(7337, 2132)

Data is splitted upon loading

In [5]:
X_train, X_ivs, y_train, col_names = pickle.load(open("drd2_data.pickle", "rb"))

In [6]:
for col in (col_names):
    print("coluna: ", col)

coluna:  D00
coluna:  D01
coluna:  D02
coluna:  D03
coluna:  D04
coluna:  D05
coluna:  D06
coluna:  D07
coluna:  D08
coluna:  D09
coluna:  D10
coluna:  D11
coluna:  D12
coluna:  D13
coluna:  D14
coluna:  D15
coluna:  D16
coluna:  D17
coluna:  D18
coluna:  D19
coluna:  D20
coluna:  D21
coluna:  D22
coluna:  D23
coluna:  D24
coluna:  D25
coluna:  D26
coluna:  D27
coluna:  D28
coluna:  D29
coluna:  D30
coluna:  D31
coluna:  D32
coluna:  D33
coluna:  D34
coluna:  D35
coluna:  D36
coluna:  D37
coluna:  D38
coluna:  D39
coluna:  D40
coluna:  D41
coluna:  D42
coluna:  FP0000
coluna:  FP0001
coluna:  FP0002
coluna:  FP0003
coluna:  FP0004
coluna:  FP0005
coluna:  FP0006
coluna:  FP0007
coluna:  FP0008
coluna:  FP0009
coluna:  FP0010
coluna:  FP0011
coluna:  FP0012
coluna:  FP0013
coluna:  FP0014
coluna:  FP0015
coluna:  FP0016
coluna:  FP0017
coluna:  FP0018
coluna:  FP0019
coluna:  FP0020
coluna:  FP0021
coluna:  FP0022
coluna:  FP0023
coluna:  FP0024
coluna:  FP0025
coluna:  FP0026
coluna:  

In [7]:
print(X_train.shape)
X_train

(7337, 2132)


array([[541.28013798, 541.656     ,  10.        , ...,   0.        ,
          0.        ,   0.        ],
       [426.19771382, 426.582     ,   5.        , ...,   0.        ,
          0.        ,   0.        ],
       [348.18377801, 348.446     ,   4.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [510.31787387, 510.802     ,   4.        , ...,   0.        ,
          0.        ,   0.        ],
       [393.18748348, 393.556     ,   4.        , ...,   0.        ,
          0.        ,   0.        ],
       [484.0561233 , 485.462     ,   6.        , ...,   0.        ,
          0.        ,   0.        ]])

In [8]:
X_train.tofile('X_train.csv', sep = ',')

In [9]:
print(X_ivs.shape)
X_ivs

(816, 2132)


array([[337.1920902 , 337.895     ,   4.        , ...,   0.        ,
          0.        ,   0.        ],
       [357.1762501 , 357.519     ,   3.        , ...,   0.        ,
          0.        ,   0.        ],
       [571.22715538, 572.171     ,   7.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [578.21338095, 578.764     ,   9.        , ...,   0.        ,
          0.        ,   0.        ],
       [311.18852904, 311.425     ,   3.        , ...,   0.        ,
          0.        ,   0.        ],
       [525.2306812 , 526.056     ,   7.        , ...,   0.        ,
          0.        ,   0.        ]])

In [10]:
print(y_train.shape)
y_train

(7337,)


array([0.65494719, 0.64999509, 0.15494719, ..., 0.2934813 , 0.59680404,
       0.77697635])

In [11]:
cols_to_discard = []
for col in range (X_train.shape[1]):
    print("coluna: ", col_names[col])
    proportion = (X_train[: col] == 0).mean() * 100
    if proportion > 0:
            print(f"Proportion of missing values in column { col }: { round(proportion, 2) }%")
    if proportion > 65:
        cols_to_discard.append(col)

coluna:  D00
coluna:  D01
Proportion of missing values in column 1: 93.01%
coluna:  D02
Proportion of missing values in column 2: 93.71%
coluna:  D03
Proportion of missing values in column 3: 93.95%
coluna:  D04
Proportion of missing values in column 4: 92.14%
coluna:  D05
Proportion of missing values in column 5: 92.51%
coluna:  D06
Proportion of missing values in column 6: 92.88%
coluna:  D07
Proportion of missing values in column 7: 93.03%
coluna:  D08
Proportion of missing values in column 8: 93.16%
coluna:  D09
Proportion of missing values in column 9: 93.16%
coluna:  D10
Proportion of missing values in column 10: 93.26%
coluna:  D11
Proportion of missing values in column 11: 93.37%
coluna:  D12
Proportion of missing values in column 12: 93.37%
coluna:  D13
Proportion of missing values in column 13: 93.37%
coluna:  D14
Proportion of missing values in column 14: 93.4%
coluna:  D15
Proportion of missing values in column 15: 93.5%
coluna:  D16
Proportion of missing values in column 1

C:\Users\joaom\AppData\Local\Temp\ipykernel_7884\3120720891.py:4: RuntimeWarning: Mean of empty slice.
  proportion = (X_train[: col] == 0).mean() * 100
c:\Users\joaom\Documents\FCUL\1ºSemestre\Aprendizagem Automática\Tp\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)



coluna:  FP0203
Proportion of missing values in column 246: 94.04%
coluna:  FP0204
Proportion of missing values in column 247: 94.04%
coluna:  FP0205
Proportion of missing values in column 248: 94.04%
coluna:  FP0206
Proportion of missing values in column 249: 94.04%
coluna:  FP0207
Proportion of missing values in column 250: 94.04%
coluna:  FP0208
Proportion of missing values in column 251: 94.05%
coluna:  FP0209
Proportion of missing values in column 252: 94.05%
coluna:  FP0210
Proportion of missing values in column 253: 94.05%
coluna:  FP0211
Proportion of missing values in column 254: 94.05%
coluna:  FP0212
Proportion of missing values in column 255: 94.04%
coluna:  FP0213
Proportion of missing values in column 256: 94.05%
coluna:  FP0214
Proportion of missing values in column 257: 94.05%
coluna:  FP0215
Proportion of missing values in column 258: 94.04%
coluna:  FP0216
Proportion of missing values in column 259: 94.04%
coluna:  FP0217
Proportion of missing values in column 260: 9

Proportion of missing values in column 383: 94.05%
coluna:  FP0341
Proportion of missing values in column 384: 94.05%
coluna:  FP0342
Proportion of missing values in column 385: 94.05%
coluna:  FP0343
Proportion of missing values in column 386: 94.05%
coluna:  FP0344
Proportion of missing values in column 387: 94.05%
coluna:  FP0345
Proportion of missing values in column 388: 94.05%
coluna:  FP0346
Proportion of missing values in column 389: 94.05%
coluna:  FP0347
Proportion of missing values in column 390: 94.06%
coluna:  FP0348
Proportion of missing values in column 391: 94.06%
coluna:  FP0349
Proportion of missing values in column 392: 94.05%
coluna:  FP0350
Proportion of missing values in column 393: 94.06%
coluna:  FP0351
Proportion of missing values in column 394: 94.06%
coluna:  FP0352
Proportion of missing values in column 395: 94.06%
coluna:  FP0353
Proportion of missing values in column 396: 94.05%
coluna:  FP0354
Proportion of missing values in column 397: 94.05%
coluna:  FP

In [12]:
N,M=X_train.shape
N,M
v=np.hstack((y_train.reshape((N,1)), X_train))
pd.DataFrame(v)

0            1         2     3     4     5     6     7      8     \
0     0.654947   541.280138   541.656  10.0   1.0   8.0   1.0  10.0   40.0   
1     0.649995   426.197714   426.582   5.0   1.0   9.0   1.0   4.0   30.0   
2     0.154947   348.183778   348.446   4.0   0.0   3.0   0.0   3.0   26.0   
3     0.616176  1455.763803  1456.831  27.0  19.0  23.0  17.0  16.0  105.0   
4     0.359725   387.151368   387.886   4.0   0.0   4.0   0.0   4.0   27.0   
...        ...          ...       ...   ...   ...   ...   ...   ...    ...   
7332  0.000000   467.149047   467.513   6.0   0.0   6.0   0.0   5.0   32.0   
7333  0.002193   240.162649   240.350   2.0   0.0   3.0   0.0   2.0   18.0   
7334  0.293481   510.317874   510.802   4.0   0.0  10.0   0.0   4.0   37.0   
7335  0.596804   393.187483   393.556   4.0   2.0   5.0   1.0   5.0   28.0   
7336  0.776976   484.056123   485.462   6.0   1.0   7.0   1.0   6.0   30.0   

       9     ...  2123  2124  2125  2126  2127  2128  2129  2130  2131  2132  
0      75.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      60.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      50.0  ...   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     206.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0  
4      50.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...     ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
7332   56.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
7333   38.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  
7334   79.0  ...   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  
7335   55.0  ...   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
7336   52.0  ...   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[7337 rows x 2133 columns]

In [32]:
corr_matrix = pd.DataFrame(np.corrcoef(v.T))

# Initialize an empty list to store line numbers and values
filtered_values_per_line = []

# Iterate through the DataFrame and store line numbers and values
for i, row in enumerate(corr_matrix.values):
    line_values = [(j, value) for j, value in enumerate(row) if abs(value) > 0.8 and abs(value) < 1]
    if line_values:
        filtered_values_per_line.append(line_values)

# Display the filtered values for each line
for line_number, values in enumerate(filtered_values_per_line):
    print(f"Line {line_number}: {values}")
   


Line 0: [(2, 0.9999983155210072), (3, 0.9193887986027773), (5, 0.8882524291334627), (7, 0.8562423033133163), (8, 0.9927658819421125), (9, 0.9731772527206053), (10, 0.9262796102354603), (11, 0.8020335705596393), (25, 0.9955919978894892), (26, 0.8895416963815175), (28, 0.9878173915638387), (29, 0.9941705912580975), (30, 0.9841447691380011), (31, 0.9297798917821187), (32, 0.9297798917821187), (33, 0.8807774464119406), (34, 0.9853821105459365), (35, 0.9759793937981859), (36, 0.9294648208413939), (37, 0.9294648208413939), (38, 0.8827314541520317), (39, -0.8853117983814768), (40, 0.989940203754323), (41, 0.9644198515929259), (42, 0.9250040193090073), (43, 0.9471245999429874)]
Line 1: [(1, 0.9999983155210072), (3, 0.9191281683353638), (5, 0.8880715732742178), (7, 0.8559797802275315), (8, 0.992622847808567), (9, 0.9729556533596053), (10, 0.9262351202640386), (11, 0.8018651856429185), (25, 0.9955315398724913), (26, 0.8892900106377305), (28, 0.9877516921825363), (29, 0.9941145769584743), (30, 0.

In [31]:
pd.DataFrame(np.corrcoef(v.T))

0         1         2         3         4         5         6     \
0     1.000000  0.160182  0.160216  0.130117  0.084939  0.151968  0.095929   
1     0.160182  1.000000  0.999998  0.919389  0.772557  0.888252  0.784495   
2     0.160216  0.999998  1.000000  0.919128  0.772379  0.888072  0.784320   
3     0.130117  0.919389  0.919128  1.000000  0.838103  0.863232  0.843652   
4     0.084939  0.772557  0.772379  0.838103  1.000000  0.704868  0.993448   
...        ...       ...       ...       ...       ...       ...       ...   
2128  0.001865  0.053576  0.053498  0.043314  0.045537  0.036037  0.047958   
2129  0.012468  0.212881  0.212889  0.181134  0.110449  0.254921  0.115041   
2130  0.031884  0.342831  0.342785  0.332638  0.409722  0.276091  0.410854   
2131 -0.027774  0.173077  0.173016  0.137266  0.210139  0.177572  0.216401   
2132  0.058370  0.219727  0.219646  0.205303  0.231743  0.119145  0.240242   

          7         8         9     ...      2123      2124      2125  \
0     0.126690  0.157545  0.165189  ...  0.011360  0.095138  0.078900   
1     0.856242  0.992766  0.973177  ...  0.213406  0.019559  0.127229   
2     0.855980  0.992623  0.972956  ...  0.213435  0.019583  0.127309   
3     0.931528  0.922469  0.905146  ...  0.196534 -0.008557  0.095891   
4     0.653117  0.774714  0.769215  ...  0.185163 -0.032325  0.083849   
...        ...       ...       ...  ...       ...       ...       ...   
2128  0.038387  0.059813  0.061989  ...  0.018420 -0.020652 -0.018922   
2129  0.202605  0.213051  0.218212  ...  0.022700 -0.015847  0.075295   
2130  0.233237  0.342548  0.342609  ...  0.006494  0.017914  0.009569   
2131  0.081396  0.184924  0.190152  ...  0.004409 -0.026145  0.009127   
2132  0.151050  0.226627  0.218560  ...  0.004474  0.000246 -0.018317   

          2126      2127      2128      2129      2130      2131      2132  
0    -0.021728 -0.012977  0.001865  0.012468  0.031884 -0.027774  0.058370  
1     0.117371 -0.017119  0.053576  0.212881  0.342831  0.173077  0.219727  
2     0.117351 -0.017201  0.053498  0.212889  0.342785  0.173016  0.219646  
3     0.064926 -0.026235  0.043314  0.181134  0.332638  0.137266  0.205303  
4     0.022735 -0.013150  0.045537  0.110449  0.409722  0.210139  0.231743  
...        ...       ...       ...       ...       ...       ...       ...  
2128 -0.009945 -0.009870  1.000000  0.063520  0.047193  0.032638  0.027846  
2129 -0.020981 -0.004391  0.063520  1.000000  0.026101  0.049729  0.000372  
2130 -0.004214 -0.020504  0.047193  0.026101  1.000000  0.123067  0.127682  
2131  0.051670 -0.029027  0.032638  0.049729  0.123067  1.000000  0.082630  
2132 -0.025196 -0.024145  0.027846  0.000372  0.127682  0.082630  1.000000  

[2133 rows x 2133 columns]

In [14]:
print(np.unique(X_train[: 1]))

[-4.31000000e+00  0.00000000e+00  3.66666667e-01  1.00000000e+00
  3.00000000e+00  3.05150000e+00  4.00000000e+00  4.57700664e+00
  5.00000000e+00  5.80131998e+00  6.00000000e+00  6.93253105e+00
  8.00000000e+00  8.07678492e+00  1.00000000e+01  1.06898607e+01
  1.39182315e+01  2.30316691e+01  2.59405851e+01  4.00000000e+01
  7.50000000e+01  9.29400000e+01  1.57216800e+02  2.31488913e+02
  5.41280138e+02  5.41656000e+02]


In [15]:
def printAvalStat(truth, preds):
    print("The RVE is: ", explained_variance_score(truth, preds))
    print("The rmse is: ", mean_squared_error(truth, preds, squared=False))
    corr, pval=pearsonr(truth, preds)
    print("The Correlation Score is: %6.4f (p-value=%e)"%(corr,pval))

    print("The Maximum Error is: ", max_error(truth, preds))
    print("The Mean Absolute Error is:", mean_absolute_error(truth, preds),"\n")

<h3>Data Treatement

In [16]:
scaler = PowerTransformer().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_ivs_scaled = scaler.transform(X_ivs)

c:\Users\joaom\Documents\FCUL\1ºSemestre\Aprendizagem Automática\Tp\Lib\site-packages\numpy\core\_methods.py:176: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
c:\Users\joaom\Documents\FCUL\1ºSemestre\Aprendizagem Automática\Tp\Lib\site-packages\numpy\core\_methods.py:187: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(x, axis, dtype, out, keepdims=keepdims, where=where)


In [17]:
print(np.unique(X_train_scaled[: 1]))

[-1.63077156 -1.07283835 -0.88437713 ... 10.496031   10.66023569
 11.40253731]


In [18]:
X_train_scaled.tofile('X_train_scaled.csv', sep = ',')

In [19]:
y_test = y_train[:816]
print(y_test.shape)
y_test

(816,)


array([0.65494719, 0.64999509, 0.15494719, 0.61617647, 0.35972465,
       0.32846835, 0.370043  , 0.4838855 , 0.32878866, 1.        ,
       0.900515  , 0.3837994 , 0.80710313, 0.47986142, 0.63821049,
       0.39999941, 0.48020469, 0.65956804, 0.        , 0.25500029,
       0.87037151, 0.        , 0.57099916, 0.29139482, 0.66944518,
       0.3634847 , 0.77154654, 0.32016718, 0.28036955, 0.59040265,
       0.44499914, 0.46346799, 0.22620766, 0.28733844, 0.50671804,
       0.14947766, 0.59163289, 0.68618187, 0.23020469, 0.        ,
       0.32310746, 0.3668114 , 0.66944518, 0.48631802, 0.        ,
       0.        , 0.1325445 , 0.68618187, 0.65404616, 0.05655339,
       0.60000196, 0.38821049, 0.3249994 , 0.0525    , 1.        ,
       1.        , 0.72151416, 0.        , 0.12715958, 0.63655578,
       0.        , 0.        , 0.46741656, 0.3768099 , 0.        ,
       0.45750062, 0.05000006, 0.58669687, 0.        , 0.70597718,
       0.31811469, 0.        , 0.23020469, 1.        , 0.19302

<h4>Principal component analisys (PCA)

In [20]:
pca = PCA(n_components=50)
pca.fit(X_train_scaled)
tve=0
for i, ve in enumerate(pca.explained_variance_ratio_):
    tve+=ve
    print("PC%d - Variance explained: %7.4f - Total Variance: %7.4f" % (i, ve, tve) )
print()
print("Actual Eigenvalues:", pca.singular_values_)
for i,comp in enumerate(pca.components_):
    print("PC",i, "-->", comp)

PC0 - Variance explained:  0.0207 - Total Variance:  0.0207
PC1 - Variance explained:  0.0133 - Total Variance:  0.0340
PC2 - Variance explained:  0.0129 - Total Variance:  0.0470
PC3 - Variance explained:  0.0124 - Total Variance:  0.0593
PC4 - Variance explained:  0.0098 - Total Variance:  0.0691
PC5 - Variance explained:  0.0078 - Total Variance:  0.0769
PC6 - Variance explained:  0.0075 - Total Variance:  0.0844
PC7 - Variance explained:  0.0070 - Total Variance:  0.0915
PC8 - Variance explained:  0.0067 - Total Variance:  0.0981
PC9 - Variance explained:  0.0064 - Total Variance:  0.1046
PC10 - Variance explained:  0.0062 - Total Variance:  0.1108
PC11 - Variance explained:  0.0059 - Total Variance:  0.1168
PC12 - Variance explained:  0.0058 - Total Variance:  0.1226
PC13 - Variance explained:  0.0056 - Total Variance:  0.1281
PC14 - Variance explained:  0.0055 - Total Variance:  0.1336
PC15 - Variance explained:  0.0051 - Total Variance:  0.1387
PC16 - Variance explained:  0.0051

In [21]:
nX_train=pca.transform(X_train_scaled)
nX_test=pca.transform(X_ivs)

<h3>Feature Selection

<h4>Stepwise fowards feature selection 

In [22]:
N,M=X_train.shape

#using linear regression for sequential feature selection
lmr=RandomForestRegressor()
sfs = SequentialFeatureSelector(lmr, n_features_to_select=50, n_jobs=16)
sfs.fit(X_train, y_train)

#get the relevant columns
features=sfs.get_support()
Features_selected =np.arange(M)[features]
print("The features selected are columns: ", Features_selected)

nXf_train=sfs.transform(X_train)
nXf_test=sfs.transform(X_ivs)

KeyboardInterrupt: 

<h4>RFs for feature selection

In [ ]:
rfr=RandomForestRegressor(random_state=0, n_jobs=8)
rfr.fit(X_train_scaled, y_train)
for i, imp in enumerate(rfr.feature_importances_):
    print("Feature", i, "Importance:", imp )

Feature 0 Importance: 0.003441489622977395
Feature 1 Importance: 0.004222959324932419
Feature 2 Importance: 0.002455890869940454
Feature 3 Importance: 0.0038397194229418674
Feature 4 Importance: 0.0038992587383474024
Feature 5 Importance: 0.0028784929302473894
Feature 6 Importance: 0.0029782344800156984
Feature 7 Importance: 0.0012503015274411
Feature 8 Importance: 0.0034638490866007433
Feature 9 Importance: 0.003526553741891764
Feature 10 Importance: 0.0016566046693172957
Feature 11 Importance: 0.019911602624642123
Feature 12 Importance: 0.0021764935364872607
Feature 13 Importance: 0.001533844482390713
Feature 14 Importance: 0.0011080855737697739
Feature 15 Importance: 0.001463219758777159
Feature 16 Importance: 0.002522881715461917
Feature 17 Importance: 0.0015307259095194913
Feature 18 Importance: 0.0008936096986832685
Feature 19 Importance: 0.0012936663056965225
Feature 20 Importance: 7.248793459917893e-05
Feature 21 Importance: 9.136104227502996e-05
Feature 22 Importance: 0.005665

<h3>Cross-validation

<h4>N-Fold Cross validation

In [ ]:
def nfold_valid(X_train_Valids):
    kf = KFold(n_splits=5, shuffle=True, random_state=23)
    kf.get_n_splits(X_train_Valids)
    TRUTH_nfold=None
    PREDS_nfold=None
    for train_index, test_index in kf.split(X_train_Valids):
        X_train_nfold, X_ivs_nfold = X_train_Valids[train_index], X_train_Valids[test_index]
        y_train_nfold, y_ivs_nfold = y_train[train_index], y_train[test_index]

        mdl = DecisionTreeRegressor()#max_depth = 5)
        mdl.fit(X_train_nfold, y_train_nfold)
        preds = mdl.predict(X_ivs_nfold)
        if TRUTH_nfold is None:
            PREDS_nfold=preds
            TRUTH_nfold=y_ivs_nfold
        else:
            PREDS_nfold=np.hstack((PREDS_nfold, preds))
            TRUTH_nfold=np.hstack((TRUTH_nfold, y_ivs_nfold))
        
    printAvalStat(TRUTH_nfold, PREDS_nfold)

print("N-fold cross validation of X_train")
nfold_valid(X_train)
print("N-fold cross validation of nX_train, after PCA")
nfold_valid(nX_train)
print("N-fold cross validation of nXf_train, after sequencial reduction feature selection")
nfold_valid(nXf_train)

N-fold cross validation of X_train
The RVE is:  0.2932045141626137
The rmse is:  0.23270235899913752
The Correlation Score is: 0.6453 (p-value=0.000000e+00)
The Maximum Error is:  1.0
The Mean Absolute Error is: 0.15981200235845713 

N-fold cross validation of nX_train, after PCA
The RVE is:  -0.31918733737141336
The rmse is:  0.31780849041790693
The Correlation Score is: 0.3505 (p-value=4.853193e-211)
The Maximum Error is:  1.0
The Mean Absolute Error is: 0.23441454040081094 

N-fold cross validation of nXf_train, after sequencial reduction feature selection


NameError: name 'nXf_train' is not defined

<h4>Leave-one-out cross validation

In [ ]:
def LeaveOneOut_val(X_train_Valids):
    loo = LeaveOneOut()
    loo.get_n_splits(X_train_Valids)

    TRUTH_loo=[]
    PREDS_loo=[]

    for train_index, test_index in loo.split(X_train_Valids):
        X_train_loo, X_test_loo = X_train_Valids[train_index], X_train_Valids[test_index]
        y_train_loo, y_test_loo = y_train[train_index], y_train[test_index]

        mdl = DecisionTreeRegressor()#max_depth = 5)
        mdl.fit(X_train_loo, y_train_loo)
        pred = mdl.predict(X_test_loo)
        PREDS_loo.append(pred)
        TRUTH_loo.append(y_test_loo)

    printAvalStat(TRUTH_nfold, PREDS_nfold)
        
print("Leave-one-out cross validation of X_train")
LeaveOneOut_val(X_train)
print("Leave-one-out cross validation of nX_train, after PCA")
LeaveOneOut_val(nX_train)
print("Leave-one-out cross validation of nXf_train, after sequencial reduction feature selection")
LeaveOneOut_val(nXf_train)

Leave-one-out cross validation of X_train


In [ ]:
#gammas = [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7]
#Cs = [1, 10, 100, 1e3, 1e4, 1e5]
#param_grid = {"gamma": gammas, "C": Cs}

#svr = SVR()
#gs = GridSearchCV(estimator=svr, param_grid=param_grid, scoring="explained_variance")
#gs=gs.fit(X_train, y_train)

#res = pd.DataFrame(gs.cv_results_)
#res = res.sort_values(by=["rank_test_score"])

<h4> Random Forest Regressor 

In [ ]:
def DisplayRegResults(y_test, preds):
    print("RVE: %7.4f"  % explained_variance_score(y_test, preds))
    print("rmse: %7.4f" % mean_squared_error(y_test, preds, squared=False))

In [ ]:
rf = RandomForestRegressor(n_estimators=10, random_state=0, min_samples_leaf=3)
rf.fit(X_train_scaled, y_train)
preds=rf.predict(X_ivs_scaled)

DisplayRegResults(y_test, preds)

<h3>Objective:<br> Produce the best regression model for y_ivs (Dependent Variable)</h3>

Decision tree Regression model

In [ ]:
dmdl = DecisionTreeRegressor(max_depth=5)
dmdl.fit(X_train, y_train)

dtr_preds=dmdl.predict(X_test)

#explained_variance_score(y_test, dtr_preds)

plt.figure(figsize=(15, 5))
r=tree.plot_tree(dmdl, filled=True)#, feature_names= df.columns)
plt.show()

In [ ]:
rmses_i = []
rmses_j = []

#def statGraph()
for i in range(1, 11):
    dmdl_i = DecisionTreeRegressor(max_depth=i)
    dmdl_i.fit(X_train, y_train)
    
    preds_i=dmdl_i.predict(X_test)
    #= explained_variance_score(y_test, preds)
    rmses_i.append(mean_squared_error(y_test, preds_i, squared=False))
    
for i in range(1, 41):
    dmdl_j = DecisionTreeRegressor(max_depth=5, min_samples_leaf= i)
    dmdl_j.fit(X_train, y_train)
    
    preds_j=dmdl_j.predict(X_test)
    #= explained_variance_score(y_test, preds)
    rmses_j.append(mean_squared_error(y_test, preds_j, squared=False))

plt.figure(figsize=(3,3))
plt.plot(range(1, 11), rmses_i)
plt.xlabel("max_depth")
plt.ylabel("rmse")
plt.grid()
plt.show()

plt.figure(figsize=(3,3))
plt.plot(range(1, 41), rmses_j)
plt.xlabel("min_samples_leaf")
plt.ylabel("rmse")
plt.grid()
plt.show()

Linear Regression model

In [ ]:
reg = LinearRegression()
reg.fit(X_train, y_train)

lr_preds=reg.predict(X_test)

#explained_variance_score(y_test, lr_preds)

Alternative linear regression model using statusmodel implementation

In [ ]:
X_tr = add_constant(X_train)
reg2=OLS(y_train,X_tr, hasconst=12).fit()
reg2.summary()

#alr_preds= reg2.predict(X_test)

Regularized linear models

Ridge Regression model

In [ ]:
ridge = Ridge(alpha=10, max_iter=9999999).fit(X_train, y_train)

print("The bias is: ",  ridge.intercept_)
print("The other parameters are: ")
#for i, beta in enumerate(ridge.coef_):
#    print("\t B%02d -> %9.3f"% (i+1, beta))

ridge_preds=ridge.predict(X_test)

Lasso Regression model

In [ ]:
lasso = Lasso(alpha=10, max_iter=9999999).fit(X_train, y_train)

print("The bias is: ",  lasso.intercept_)
print("The other parameters are: ")
#for i, beta in enumerate(ridge.coef_):
#    print("\t B%02d -> %9.3f"% (i+1, beta))

lasso_preds= lasso.predict(X_test)

Gráficos

In [ ]:
def drawGraf(preds, title):
    plt.figure(figsize=(3,3))
    plt.scatter(preds, y_test)
    plt.plot((0, 150), (0,150), c="r")
    plt.grid()
    plt.xlabel("Predicted")
    plt.ylabel("Truth")
    plt.title(title)
    plt.show()


#####  Gráfico linear regression #########
drawGraf(lr_preds, "Linear Regression")

#####  Gráfico decision tree regression #########
drawGraf(dtr_preds, "Decision Tree Regression")

#####  Gráfico ridge regression #########
drawGraf(ridge_preds, "Ridge Regression")

#####  Gráfico lasso regression #########
drawGraf(lasso_preds, "Lasso Regression")

In [ ]:
def printAvalStat(truth, preds):
    print("The RVE is: ", explained_variance_score(truth, preds))
    print("The rmse is: ", mean_squared_error(truth, preds, squared=False))
    corr, pval=pearsonr(truth, preds)
    print("The Correlation Score is: %6.4f (p-value=%e)"%(corr,pval))

    print("The Maximum Error is: ", max_error(truth, preds))
    print("The Mean Absolute Error is:", mean_absolute_error(truth, preds),"\n")

In [ ]:
###############   Métricas de avaliação de decision tree regression
print("Métricas de avaliação de decision tree regression:")
printAvalStat(y_test, dtr_preds)

###############   Métricas de avaliação de linear regression
print("Métricas de avaliação de linear regression:")
printAvalStat(y_test, lr_preds)

###############   Métricas de avaliação de ridge regression
print("Métricas de avaliação de ridge regression:")
printAvalStat(y_test, ridge_preds)

###############   Métricas de avaliação de lasso regression
print("Métricas de avaliação de lasso regression:")
printAvalStat(y_test, lasso_preds)