# Machine Learning 2023/2024

## Third Home Assignment

**Group Number:** 10

**Group Elements:**
- André Santos (fc53323)
- Filipe Santos (fc53304)
- João Martins (fc62532)
- Rúben Torres (fc62531)

**Hours Worked:**
- André Santos (10h)
- Filipe Santos (10h)
- João Martins (10h)
- Rúben Torres (10h)

### Imports

In [56]:
import pandas as pd
import pickle
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier, plot_tree
from sklearn.linear_model import LinearRegression, Ridge, Lasso, LogisticRegression
from statsmodels.api import OLS, add_constant
from sklearn.ensemble import RandomForestRegressor
import matplotlib.pyplot as plt
from sklearn.metrics import explained_variance_score, mean_squared_error, max_error, mean_absolute_error
from scipy.stats import pearsonr
from sklearn import tree
from sklearn.metrics import precision_score, recall_score, f1_score, matthews_corrcoef, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import (
    PowerTransformer
)

### Loading and understanding the Dataset

In [14]:
unpickled_df = pd.read_pickle("drd2_data.pickle")
unpickled_df

(array([[541.28013798, 541.656     ,  10.        , ...,   0.        ,
           0.        ,   0.        ],
        [426.19771382, 426.582     ,   5.        , ...,   0.        ,
           0.        ,   0.        ],
        [348.18377801, 348.446     ,   4.        , ...,   0.        ,
           0.        ,   0.        ],
        ...,
        [510.31787387, 510.802     ,   4.        , ...,   0.        ,
           0.        ,   0.        ],
        [393.18748348, 393.556     ,   4.        , ...,   0.        ,
           0.        ,   0.        ],
        [484.0561233 , 485.462     ,   6.        , ...,   0.        ,
           0.        ,   0.        ]]),
 array([[337.1920902 , 337.895     ,   4.        , ...,   0.        ,
           0.        ,   0.        ],
        [357.1762501 , 357.519     ,   3.        , ...,   0.        ,
           0.        ,   0.        ],
        [571.22715538, 572.171     ,   7.        , ...,   0.        ,
           0.        ,   0.        ],
        ...,


In [26]:
print(type(unpickled_df[0]))
unpickled_df[0].shape

<class 'numpy.ndarray'>


(7337, 2132)

In [2]:
X_train, X_ivs, y_train, col_names = pickle.load(open("drd2_data.pickle", "rb"))

In [35]:
for col in (col_names):
    print("coluna: ", col)

coluna:  D00
coluna:  D01
coluna:  D02
coluna:  D03
coluna:  D04
coluna:  D05
coluna:  D06
coluna:  D07
coluna:  D08
coluna:  D09
coluna:  D10
coluna:  D11
coluna:  D12
coluna:  D13
coluna:  D14
coluna:  D15
coluna:  D16
coluna:  D17
coluna:  D18
coluna:  D19
coluna:  D20
coluna:  D21
coluna:  D22
coluna:  D23
coluna:  D24
coluna:  D25
coluna:  D26
coluna:  D27
coluna:  D28
coluna:  D29
coluna:  D30
coluna:  D31
coluna:  D32
coluna:  D33
coluna:  D34
coluna:  D35
coluna:  D36
coluna:  D37
coluna:  D38
coluna:  D39
coluna:  D40
coluna:  D41
coluna:  D42
coluna:  FP0000
coluna:  FP0001
coluna:  FP0002
coluna:  FP0003
coluna:  FP0004
coluna:  FP0005
coluna:  FP0006
coluna:  FP0007
coluna:  FP0008
coluna:  FP0009
coluna:  FP0010
coluna:  FP0011
coluna:  FP0012
coluna:  FP0013
coluna:  FP0014
coluna:  FP0015
coluna:  FP0016
coluna:  FP0017
coluna:  FP0018
coluna:  FP0019
coluna:  FP0020
coluna:  FP0021
coluna:  FP0022
coluna:  FP0023
coluna:  FP0024
coluna:  FP0025
coluna:  FP0026
coluna:  

In [60]:
print(X_train.shape)
X_train

(7337, 2132)


array([[541.28013798, 541.656     ,  10.        , ...,   0.        ,
          0.        ,   0.        ],
       [426.19771382, 426.582     ,   5.        , ...,   0.        ,
          0.        ,   0.        ],
       [348.18377801, 348.446     ,   4.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [510.31787387, 510.802     ,   4.        , ...,   0.        ,
          0.        ,   0.        ],
       [393.18748348, 393.556     ,   4.        , ...,   0.        ,
          0.        ,   0.        ],
       [484.0561233 , 485.462     ,   6.        , ...,   0.        ,
          0.        ,   0.        ]])

In [43]:
X_train.tofile('X_train.csv', sep = ',')

In [62]:
print(X_ivs.shape)
X_ivs

(816, 2132)


array([[337.1920902 , 337.895     ,   4.        , ...,   0.        ,
          0.        ,   0.        ],
       [357.1762501 , 357.519     ,   3.        , ...,   0.        ,
          0.        ,   0.        ],
       [571.22715538, 572.171     ,   7.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [578.21338095, 578.764     ,   9.        , ...,   0.        ,
          0.        ,   0.        ],
       [311.18852904, 311.425     ,   3.        , ...,   0.        ,
          0.        ,   0.        ],
       [525.2306812 , 526.056     ,   7.        , ...,   0.        ,
          0.        ,   0.        ]])

In [63]:
print(y_train.shape)
y_train

(7337,)


array([0.65494719, 0.64999509, 0.15494719, ..., 0.2934813 , 0.59680404,
       0.77697635])

In [42]:
cols_to_discard = []
for col in range (X_train.shape[1]):
    print("coluna: ", col_names[col])
    proportion = (X_train[: col] == 0).mean() * 100
    if proportion > 0:
            print(f"Proportion of missing values in column { col }: { round(proportion, 2) }%")
    if proportion > 65:
        cols_to_discard.append(col)

coluna:  D00
coluna:  D01
Proportion of missing values in column 1: 93.01%
coluna:  D02
Proportion of missing values in column 2: 93.71%
coluna:  D03
Proportion of missing values in column 3: 93.95%
coluna:  D04
Proportion of missing values in column 4: 92.14%
coluna:  D05
Proportion of missing values in column 5: 92.51%
coluna:  D06
Proportion of missing values in column 6: 92.88%
coluna:  D07
Proportion of missing values in column 7: 93.03%
coluna:  D08
Proportion of missing values in column 8: 93.16%
coluna:  D09
Proportion of missing values in column 9: 93.16%
coluna:  D10
Proportion of missing values in column 10: 93.26%
coluna:  D11
Proportion of missing values in column 11: 93.37%
coluna:  D12
Proportion of missing values in column 12: 93.37%
coluna:  D13
Proportion of missing values in column 13: 93.37%
coluna:  D14
Proportion of missing values in column 14: 93.4%
coluna:  D15
Proportion of missing values in column 15: 93.5%
coluna:  D16
Proportion of missing values in column 1

C:\Users\TeamSantoes\AppData\Local\Temp\ipykernel_17772\3120720891.py:4: RuntimeWarning: Mean of empty slice.
  proportion = (X_train[: col] == 0).mean() * 100


Proportion of missing values in column 343: 94.02%
coluna:  FP0301
Proportion of missing values in column 344: 94.03%
coluna:  FP0302
Proportion of missing values in column 345: 94.03%
coluna:  FP0303
Proportion of missing values in column 346: 94.02%
coluna:  FP0304
Proportion of missing values in column 347: 94.03%
coluna:  FP0305
Proportion of missing values in column 348: 94.02%
coluna:  FP0306
Proportion of missing values in column 349: 94.03%
coluna:  FP0307
Proportion of missing values in column 350: 94.02%
coluna:  FP0308
Proportion of missing values in column 351: 94.03%
coluna:  FP0309
Proportion of missing values in column 352: 94.03%
coluna:  FP0310
Proportion of missing values in column 353: 94.03%
coluna:  FP0311
Proportion of missing values in column 354: 94.03%
coluna:  FP0312
Proportion of missing values in column 355: 94.03%
coluna:  FP0313
Proportion of missing values in column 356: 94.03%
coluna:  FP0314
Proportion of missing values in column 357: 94.03%
coluna:  FP

Proportion of missing values in column 481: 94.06%
coluna:  FP0439
Proportion of missing values in column 482: 94.06%
coluna:  FP0440
Proportion of missing values in column 483: 94.06%
coluna:  FP0441
Proportion of missing values in column 484: 94.07%
coluna:  FP0442
Proportion of missing values in column 485: 94.07%
coluna:  FP0443
Proportion of missing values in column 486: 94.07%
coluna:  FP0444
Proportion of missing values in column 487: 94.07%
coluna:  FP0445
Proportion of missing values in column 488: 94.07%
coluna:  FP0446
Proportion of missing values in column 489: 94.07%
coluna:  FP0447
Proportion of missing values in column 490: 94.07%
coluna:  FP0448
Proportion of missing values in column 491: 94.07%
coluna:  FP0449
Proportion of missing values in column 492: 94.08%
coluna:  FP0450
Proportion of missing values in column 493: 94.08%
coluna:  FP0451
Proportion of missing values in column 494: 94.08%
coluna:  FP0452
Proportion of missing values in column 495: 94.08%
coluna:  FP

Proportion of missing values in column 648: 94.12%
coluna:  FP0606
Proportion of missing values in column 649: 94.12%
coluna:  FP0607
Proportion of missing values in column 650: 94.12%
coluna:  FP0608
Proportion of missing values in column 651: 94.12%
coluna:  FP0609
Proportion of missing values in column 652: 94.12%
coluna:  FP0610
Proportion of missing values in column 653: 94.12%
coluna:  FP0611
Proportion of missing values in column 654: 94.12%
coluna:  FP0612
Proportion of missing values in column 655: 94.12%
coluna:  FP0613
Proportion of missing values in column 656: 94.12%
coluna:  FP0614
Proportion of missing values in column 657: 94.12%
coluna:  FP0615
Proportion of missing values in column 658: 94.12%
coluna:  FP0616
Proportion of missing values in column 659: 94.12%
coluna:  FP0617
Proportion of missing values in column 660: 94.12%
coluna:  FP0618
Proportion of missing values in column 661: 94.12%
coluna:  FP0619
Proportion of missing values in column 662: 94.12%
coluna:  FP

Proportion of missing values in column 789: 94.13%
coluna:  FP0747
Proportion of missing values in column 790: 94.12%
coluna:  FP0748
Proportion of missing values in column 791: 94.12%
coluna:  FP0749
Proportion of missing values in column 792: 94.13%
coluna:  FP0750
Proportion of missing values in column 793: 94.13%
coluna:  FP0751
Proportion of missing values in column 794: 94.12%
coluna:  FP0752
Proportion of missing values in column 795: 94.13%
coluna:  FP0753
Proportion of missing values in column 796: 94.13%
coluna:  FP0754
Proportion of missing values in column 797: 94.13%
coluna:  FP0755
Proportion of missing values in column 798: 94.13%
coluna:  FP0756
Proportion of missing values in column 799: 94.13%
coluna:  FP0757
Proportion of missing values in column 800: 94.13%
coluna:  FP0758
Proportion of missing values in column 801: 94.13%
coluna:  FP0759
Proportion of missing values in column 802: 94.13%
coluna:  FP0760
Proportion of missing values in column 803: 94.13%
coluna:  FP

Proportion of missing values in column 965: 94.07%
coluna:  FP0923
Proportion of missing values in column 966: 94.07%
coluna:  FP0924
Proportion of missing values in column 967: 94.07%
coluna:  FP0925
Proportion of missing values in column 968: 94.07%
coluna:  FP0926
Proportion of missing values in column 969: 94.07%
coluna:  FP0927
Proportion of missing values in column 970: 94.07%
coluna:  FP0928
Proportion of missing values in column 971: 94.07%
coluna:  FP0929
Proportion of missing values in column 972: 94.07%
coluna:  FP0930
Proportion of missing values in column 973: 94.07%
coluna:  FP0931
Proportion of missing values in column 974: 94.07%
coluna:  FP0932
Proportion of missing values in column 975: 94.08%
coluna:  FP0933
Proportion of missing values in column 976: 94.08%
coluna:  FP0934
Proportion of missing values in column 977: 94.08%
coluna:  FP0935
Proportion of missing values in column 978: 94.08%
coluna:  FP0936
Proportion of missing values in column 979: 94.08%
coluna:  FP

Proportion of missing values in column 1107: 94.08%
coluna:  FP1065
Proportion of missing values in column 1108: 94.08%
coluna:  FP1066
Proportion of missing values in column 1109: 94.08%
coluna:  FP1067
Proportion of missing values in column 1110: 94.08%
coluna:  FP1068
Proportion of missing values in column 1111: 94.08%
coluna:  FP1069
Proportion of missing values in column 1112: 94.08%
coluna:  FP1070
Proportion of missing values in column 1113: 94.08%
coluna:  FP1071
Proportion of missing values in column 1114: 94.08%
coluna:  FP1072
Proportion of missing values in column 1115: 94.08%
coluna:  FP1073
Proportion of missing values in column 1116: 94.08%
coluna:  FP1074
Proportion of missing values in column 1117: 94.08%
coluna:  FP1075
Proportion of missing values in column 1118: 94.08%
coluna:  FP1076
Proportion of missing values in column 1119: 94.08%
coluna:  FP1077
Proportion of missing values in column 1120: 94.08%
coluna:  FP1078
Proportion of missing values in column 1121: 94.

Proportion of missing values in column 1234: 94.08%
coluna:  FP1192
Proportion of missing values in column 1235: 94.08%
coluna:  FP1193
Proportion of missing values in column 1236: 94.08%
coluna:  FP1194
Proportion of missing values in column 1237: 94.08%
coluna:  FP1195
Proportion of missing values in column 1238: 94.08%
coluna:  FP1196
Proportion of missing values in column 1239: 94.08%
coluna:  FP1197
Proportion of missing values in column 1240: 94.08%
coluna:  FP1198
Proportion of missing values in column 1241: 94.08%
coluna:  FP1199
Proportion of missing values in column 1242: 94.08%
coluna:  FP1200
Proportion of missing values in column 1243: 94.08%
coluna:  FP1201
Proportion of missing values in column 1244: 94.08%
coluna:  FP1202
Proportion of missing values in column 1245: 94.08%
coluna:  FP1203
Proportion of missing values in column 1246: 94.08%
coluna:  FP1204
Proportion of missing values in column 1247: 94.08%
coluna:  FP1205
Proportion of missing values in column 1248: 94.

Proportion of missing values in column 1385: 94.1%
coluna:  FP1343
Proportion of missing values in column 1386: 94.1%
coluna:  FP1344
Proportion of missing values in column 1387: 94.1%
coluna:  FP1345
Proportion of missing values in column 1388: 94.1%
coluna:  FP1346
Proportion of missing values in column 1389: 94.1%
coluna:  FP1347
Proportion of missing values in column 1390: 94.1%
coluna:  FP1348
Proportion of missing values in column 1391: 94.1%
coluna:  FP1349
Proportion of missing values in column 1392: 94.1%
coluna:  FP1350
Proportion of missing values in column 1393: 94.1%
coluna:  FP1351
Proportion of missing values in column 1394: 94.1%
coluna:  FP1352
Proportion of missing values in column 1395: 94.1%
coluna:  FP1353
Proportion of missing values in column 1396: 94.1%
coluna:  FP1354
Proportion of missing values in column 1397: 94.1%
coluna:  FP1355
Proportion of missing values in column 1398: 94.1%
coluna:  FP1356
Proportion of missing values in column 1399: 94.1%
coluna:  FP

Proportion of missing values in column 1518: 94.1%
coluna:  FP1476
Proportion of missing values in column 1519: 94.1%
coluna:  FP1477
Proportion of missing values in column 1520: 94.1%
coluna:  FP1478
Proportion of missing values in column 1521: 94.1%
coluna:  FP1479
Proportion of missing values in column 1522: 94.1%
coluna:  FP1480
Proportion of missing values in column 1523: 94.1%
coluna:  FP1481
Proportion of missing values in column 1524: 94.1%
coluna:  FP1482
Proportion of missing values in column 1525: 94.1%
coluna:  FP1483
Proportion of missing values in column 1526: 94.1%
coluna:  FP1484
Proportion of missing values in column 1527: 94.1%
coluna:  FP1485
Proportion of missing values in column 1528: 94.1%
coluna:  FP1486
Proportion of missing values in column 1529: 94.1%
coluna:  FP1487
Proportion of missing values in column 1530: 94.1%
coluna:  FP1488
Proportion of missing values in column 1531: 94.1%
coluna:  FP1489
Proportion of missing values in column 1532: 94.1%
coluna:  FP

Proportion of missing values in column 1660: 94.12%
coluna:  FP1618
Proportion of missing values in column 1661: 94.11%
coluna:  FP1619
Proportion of missing values in column 1662: 94.12%
coluna:  FP1620
Proportion of missing values in column 1663: 94.12%
coluna:  FP1621
Proportion of missing values in column 1664: 94.12%
coluna:  FP1622
Proportion of missing values in column 1665: 94.11%
coluna:  FP1623
Proportion of missing values in column 1666: 94.11%
coluna:  FP1624
Proportion of missing values in column 1667: 94.12%
coluna:  FP1625
Proportion of missing values in column 1668: 94.12%
coluna:  FP1626
Proportion of missing values in column 1669: 94.11%
coluna:  FP1627
Proportion of missing values in column 1670: 94.11%
coluna:  FP1628
Proportion of missing values in column 1671: 94.11%
coluna:  FP1629
Proportion of missing values in column 1672: 94.12%
coluna:  FP1630
Proportion of missing values in column 1673: 94.11%
coluna:  FP1631
Proportion of missing values in column 1674: 94.

Proportion of missing values in column 1805: 94.12%
coluna:  FP1763
Proportion of missing values in column 1806: 94.12%
coluna:  FP1764
Proportion of missing values in column 1807: 94.12%
coluna:  FP1765
Proportion of missing values in column 1808: 94.12%
coluna:  FP1766
Proportion of missing values in column 1809: 94.12%
coluna:  FP1767
Proportion of missing values in column 1810: 94.12%
coluna:  FP1768
Proportion of missing values in column 1811: 94.12%
coluna:  FP1769
Proportion of missing values in column 1812: 94.12%
coluna:  FP1770
Proportion of missing values in column 1813: 94.12%
coluna:  FP1771
Proportion of missing values in column 1814: 94.12%
coluna:  FP1772
Proportion of missing values in column 1815: 94.12%
coluna:  FP1773
Proportion of missing values in column 1816: 94.12%
coluna:  FP1774
Proportion of missing values in column 1817: 94.12%
coluna:  FP1775
Proportion of missing values in column 1818: 94.12%
coluna:  FP1776
Proportion of missing values in column 1819: 94.

Proportion of missing values in column 1938: 94.12%
coluna:  FP1896
Proportion of missing values in column 1939: 94.12%
coluna:  FP1897
Proportion of missing values in column 1940: 94.12%
coluna:  FP1898
Proportion of missing values in column 1941: 94.12%
coluna:  FP1899
Proportion of missing values in column 1942: 94.12%
coluna:  FP1900
Proportion of missing values in column 1943: 94.12%
coluna:  FP1901
Proportion of missing values in column 1944: 94.12%
coluna:  FP1902
Proportion of missing values in column 1945: 94.12%
coluna:  FP1903
Proportion of missing values in column 1946: 94.12%
coluna:  FP1904
Proportion of missing values in column 1947: 94.12%
coluna:  FP1905
Proportion of missing values in column 1948: 94.12%
coluna:  FP1906
Proportion of missing values in column 1949: 94.12%
coluna:  FP1907
Proportion of missing values in column 1950: 94.12%
coluna:  FP1908
Proportion of missing values in column 1951: 94.12%
coluna:  FP1909
Proportion of missing values in column 1952: 94.

Proportion of missing values in column 2081: 94.12%
coluna:  FP2039
Proportion of missing values in column 2082: 94.12%
coluna:  FP2040
Proportion of missing values in column 2083: 94.12%
coluna:  FP2041
Proportion of missing values in column 2084: 94.12%
coluna:  FP2042
Proportion of missing values in column 2085: 94.12%
coluna:  FP2043
Proportion of missing values in column 2086: 94.12%
coluna:  FP2044
Proportion of missing values in column 2087: 94.12%
coluna:  FP2045
Proportion of missing values in column 2088: 94.12%
coluna:  FP2046
Proportion of missing values in column 2089: 94.12%
coluna:  FP2047
Proportion of missing values in column 2090: 94.12%
coluna:  FP2048
Proportion of missing values in column 2091: 94.12%
coluna:  FP2049
Proportion of missing values in column 2092: 94.12%
coluna:  FP2050
Proportion of missing values in column 2093: 94.12%
coluna:  FP2051
Proportion of missing values in column 2094: 94.12%
coluna:  FP2052
Proportion of missing values in column 2095: 94.

In [49]:
print(np.unique(X_train[: 1]))

[-4.31000000e+00  0.00000000e+00  3.66666667e-01  1.00000000e+00
  3.00000000e+00  3.05150000e+00  4.00000000e+00  4.57700664e+00
  5.00000000e+00  5.80131998e+00  6.00000000e+00  6.93253105e+00
  8.00000000e+00  8.07678492e+00  1.00000000e+01  1.06898607e+01
  1.39182315e+01  2.30316691e+01  2.59405851e+01  4.00000000e+01
  7.50000000e+01  9.29400000e+01  1.57216800e+02  2.31488913e+02
  5.41280138e+02  5.41656000e+02]


<h3>Data Treatement

In [52]:
scaler = PowerTransformer().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_ivs_scaled = scaler.transform(X_ivs)

D:\programs\anaconda3\lib\site-packages\numpy\core\_methods.py:236: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)
D:\programs\anaconda3\lib\site-packages\numpy\core\_methods.py:247: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(x, axis, dtype, out, keepdims=keepdims, where=where)


In [53]:
print(np.unique(X_train_scaled[: 1]))

[-1.63077156 -1.07283835 -0.88437713 ... 10.496031   10.66023569
 11.40253731]


In [54]:
X_train_scaled.tofile('X_train_scaled.csv', sep = ',')

<h3>Finguring out the Dependent Variable (Column)</h3>

In [67]:
y_test = y_train[:816]
print(y_test.shape)
y_test

(816,)


array([0.65494719, 0.64999509, 0.15494719, 0.61617647, 0.35972465,
       0.32846835, 0.370043  , 0.4838855 , 0.32878866, 1.        ,
       0.900515  , 0.3837994 , 0.80710313, 0.47986142, 0.63821049,
       0.39999941, 0.48020469, 0.65956804, 0.        , 0.25500029,
       0.87037151, 0.        , 0.57099916, 0.29139482, 0.66944518,
       0.3634847 , 0.77154654, 0.32016718, 0.28036955, 0.59040265,
       0.44499914, 0.46346799, 0.22620766, 0.28733844, 0.50671804,
       0.14947766, 0.59163289, 0.68618187, 0.23020469, 0.        ,
       0.32310746, 0.3668114 , 0.66944518, 0.48631802, 0.        ,
       0.        , 0.1325445 , 0.68618187, 0.65404616, 0.05655339,
       0.60000196, 0.38821049, 0.3249994 , 0.0525    , 1.        ,
       1.        , 0.72151416, 0.        , 0.12715958, 0.63655578,
       0.        , 0.        , 0.46741656, 0.3768099 , 0.        ,
       0.45750062, 0.05000006, 0.58669687, 0.        , 0.70597718,
       0.31811469, 0.        , 0.23020469, 1.        , 0.19302

<h4> Random Forest Regressor 

In [58]:
def DisplayRegResults(y_test, preds):
    print("RVE: %7.4f"  % explained_variance_score(y_test, preds))
    print("rmse: %7.4f" % mean_squared_error(y_test, preds, squared=False))

In [69]:
rf = RandomForestRegressor(n_estimators=10, random_state=0, min_samples_leaf=3)
rf.fit(X_train_scaled, y_train)
preds=rf.predict(X_ivs_scaled)

DisplayRegResults(y_test, preds)

RVE: -0.6359
rmse:  0.3358


<h3>Objective:<br> Produce the best regression model for y_ivs (Dependent Variable)</h3>

Decision tree Regression model

In [ ]:
dmdl = DecisionTreeRegressor(max_depth=5)
dmdl.fit(X_train, y_train)

dtr_preds=dmdl.predict(X_test)

#explained_variance_score(y_test, dtr_preds)

plt.figure(figsize=(15, 5))
r=tree.plot_tree(dmdl, filled=True)#, feature_names= df.columns)
plt.show()

In [ ]:
rmses_i = []
rmses_j = []

#def statGraph()
for i in range(1, 11):
    dmdl_i = DecisionTreeRegressor(max_depth=i)
    dmdl_i.fit(X_train, y_train)
    
    preds_i=dmdl_i.predict(X_test)
    #= explained_variance_score(y_test, preds)
    rmses_i.append(mean_squared_error(y_test, preds_i, squared=False))
    
for i in range(1, 41):
    dmdl_j = DecisionTreeRegressor(max_depth=5, min_samples_leaf= i)
    dmdl_j.fit(X_train, y_train)
    
    preds_j=dmdl_j.predict(X_test)
    #= explained_variance_score(y_test, preds)
    rmses_j.append(mean_squared_error(y_test, preds_j, squared=False))

plt.figure(figsize=(3,3))
plt.plot(range(1, 11), rmses_i)
plt.xlabel("max_depth")
plt.ylabel("rmse")
plt.grid()
plt.show()

plt.figure(figsize=(3,3))
plt.plot(range(1, 41), rmses_j)
plt.xlabel("min_samples_leaf")
plt.ylabel("rmse")
plt.grid()
plt.show()

Linear Regression model

In [ ]:
reg = LinearRegression()
reg.fit(X_train, y_train)

lr_preds=reg.predict(X_test)

#explained_variance_score(y_test, lr_preds)

Alternative linear regression model using statusmodel implementation

In [ ]:
X_tr = add_constant(X_train)
reg2=OLS(y_train,X_tr, hasconst=12).fit()
reg2.summary()

#alr_preds= reg2.predict(X_test)

Regularized linear models

Ridge Regression model

In [ ]:
ridge = Ridge(alpha=10, max_iter=9999999).fit(X_train, y_train)

print("The bias is: ",  ridge.intercept_)
print("The other parameters are: ")
#for i, beta in enumerate(ridge.coef_):
#    print("\t B%02d -> %9.3f"% (i+1, beta))

ridge_preds=ridge.predict(X_test)

Lasso Regression model

In [ ]:
lasso = Lasso(alpha=10, max_iter=9999999).fit(X_train, y_train)

print("The bias is: ",  lasso.intercept_)
print("The other parameters are: ")
#for i, beta in enumerate(ridge.coef_):
#    print("\t B%02d -> %9.3f"% (i+1, beta))

lasso_preds= lasso.predict(X_test)

Gráficos

In [ ]:
def drawGraf(preds, title):
    plt.figure(figsize=(3,3))
    plt.scatter(preds, y_test)
    plt.plot((0, 150), (0,150), c="r")
    plt.grid()
    plt.xlabel("Predicted")
    plt.ylabel("Truth")
    plt.title(title)
    plt.show()


#####  Gráfico linear regression #########
drawGraf(lr_preds, "Linear Regression")

#####  Gráfico decision tree regression #########
drawGraf(dtr_preds, "Decision Tree Regression")

#####  Gráfico ridge regression #########
drawGraf(ridge_preds, "Ridge Regression")

#####  Gráfico lasso regression #########
drawGraf(lasso_preds, "Lasso Regression")

In [ ]:
def printAvalStat(truth, preds):
    print("The RVE is: ", explained_variance_score(truth, preds))
    print("The rmse is: ", mean_squared_error(truth, preds, squared=False))
    corr, pval=pearsonr(truth, preds)
    print("The Correlation Score is: %6.4f (p-value=%e)"%(corr,pval))

    print("The Maximum Error is: ", max_error(truth, preds))
    print("The Mean Absolute Error is:", mean_absolute_error(truth, preds),"\n")

In [ ]:
###############   Métricas de avaliação de decision tree regression
print("Métricas de avaliação de decision tree regression:")
printAvalStat(y_test, dtr_preds)

###############   Métricas de avaliação de linear regression
print("Métricas de avaliação de linear regression:")
printAvalStat(y_test, lr_preds)

###############   Métricas de avaliação de ridge regression
print("Métricas de avaliação de ridge regression:")
printAvalStat(y_test, ridge_preds)

###############   Métricas de avaliação de lasso regression
print("Métricas de avaliação de lasso regression:")
printAvalStat(y_test, lasso_preds)